# Generated by Django 5.1.2 on 2025-03-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
