# Generated by Django 5.1.2 on 2025-03-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_alter_newssource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.category'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Full Content'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.newssource'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(unique=True, verbose_name='Article URL'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='News Source Name'),
        ),
        migrations.AlterField(
            model_name='rsslink',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
