# Generated by Django 5.1.2 on 2025-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name_alter_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('url', models.URLField(unique=True, verbose_name='RSS Feed URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rsslink',
            name='source',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.DeleteModel(
            name='RSSLink',
        ),
    ]
