# Generated by Django 5.1.2 on 2025-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rssfeed_remove_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
